
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 123
    username: root
    url: jdbc:mysql://localhost:3306/marketdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
server:
  port: 8080

mybatis:
  mapper-locations: classpath:**/*.xml
  type-aliases-package: com.example.market.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

